# ==============================================================================
# 全域設定檔 for 量化交易模型 v11.0 (H1 核心策略版)
# ==============================================================================

# --- 路徑設定 ---
paths:
  raw_data: "Output_Data_Pipeline_v2/MarketData"
  features_data: "Output_Feature_Engineering/MarketData_with_Combined_Features_v3"
  ml_pipeline_output: "Output_ML_Pipeline"

# --- 標籤與特徵篩選設定 ---
feature_selection:
  top_n_features: 20
  lgbm_params:
    objective: 'binary'
    metric: 'binary_logloss'
    boosting_type: 'gbdt'
    n_estimators: 200
    learning_rate: 0.05
    num_leaves: 31
    max_depth: -1
    seed: 42
    n_jobs: -1
    verbose: -1

# --- 動態三道門檻標籤法設定 (已為 H1 週期調優) ---
triple_barrier_settings:
  tp_atr_multiplier: 1.5      # H1 週期止盈目標相對較小
  sl_atr_multiplier: 1.5      # H1 週期止損也相對收緊
  max_hold_periods: 48        # H1 K棒的持倉週期 (48根 = 2天)

# --- 滾動優化與回測設定 ---
walk_forward_optimization:
  # ★★★ 核心：將所有流程聚焦於 H1 ★★★
  target_timeframe: "H1"
  
  n_trials: 50                # 在 H1 上進行更充分的參數搜索
  training_days: 270
  validation_days: 90
  testing_days: 45
  step_days: 45
  initial_cash: 100000.0
  commission: 0.001

# --- 交易策略參數 (此為 Optuna 搜索的基礎，非最終參數) ---
strategy_params:
  entry_threshold: 0.52       # 降低基礎入場門檻，讓 Optuna 從更寬的範圍搜索
  risk_per_trade: 0.015       # 基礎風險設定
