# ==============================================================================
# 全域設定檔 for 量化交易模型 v10.1 (週期參數化版)
# ==============================================================================

# --- 路徑設定 ---
paths:
  raw_data: "Output_Data_Pipeline_v2/MarketData"
  features_data: "Output_Feature_Engineering/MarketData_with_Combined_Features_v3"
  ml_pipeline_output: "Output_ML_Pipeline"
  selected_features_filename: "selected_features.json"

# --- 標籤與特徵篩選設定 (用於 03_feature_selection.py) ---
# 注意：標籤設定已與 04 腳本同步，由下方的 triple_barrier_settings 控制
feature_selection:
  top_n_features: 20
  lgbm_params:
    objective: 'binary'
    metric: 'binary_logloss'
    boosting_type: 'gbdt'
    n_estimators: 200
    learning_rate: 0.05
    num_leaves: 31
    max_depth: -1
    seed: 42
    n_jobs: -1
    verbose: -1

# --- 動態三道門檻標籤法設定 (ATR-Based) ---
# 這是目前策略的核心定義，同時被 03 和 04 腳本使用
triple_barrier_settings:
  tp_atr_multiplier: 1.5      
  sl_atr_multiplier: 1.5      
  max_hold_periods: 48        

# --- 滾動優化與回測設定 ---
walk_forward_optimization:
  # ★★★ 新增參數：指定模型優化的目標時間週期 ("H1", "H4", or "D1") ★★★
  target_timeframe: "H1"
  n_trials: 30                # [優化] 增加 Optuna 試驗次數，從 5 -> 30，進行更充分的參數搜索
  training_days: 270
  validation_days: 90
  testing_days: 45
  step_days: 45
  initial_cash: 100000.0
  commission: 0.001

# --- 交易策略參數 ---
strategy_params:
  entry_threshold: 0.35       # [優化] 降低基礎入場門檻，從 0.45 -> 0.35，增加交易機會
  risk_per_trade: 0.015       # [優化] 稍微增加基礎風險，從 0.01 -> 0.015，提升潛在收益
