# ==============================================================================
# 全域設定檔 for 量化交易模型 v5.0 (Phase 2)
# ==============================================================================

# --- 路徑設定 ---
paths:
  raw_data: "Output_Data_Pipeline_v2/MarketData"
  features_data: "Output_Feature_Engineering/MarketData_with_Combined_Features_v3"
  ml_pipeline_output: "Output_ML_Pipeline"
  selected_features_filename: "selected_features.json"

# --- 標籤與特徵篩選設定 (用於 03_feature_selection.py) ---
# ★★★ Phase 2 中，04 腳本將不再使用此區塊的標籤設定 ★★★
feature_selection:
  label_look_forward_periods: 12
  label_return_threshold: 0.003
  top_n_features: 20
  lgbm_params:
    objective: 'binary'
    metric: 'binary_logloss'
    boosting_type: 'gbdt'
    n_estimators: 200
    learning_rate: 0.05
    num_leaves: 31
    max_depth: -1
    seed: 42
    n_jobs': -1
    verbose: -1

# --- ★★★ 新增：三道門檻標籤法設定 (用於 04_parameter_optimization.py) ★★★ ---
triple_barrier_settings:
  tp_atr_multiplier: 2.5  # 停利目標為 2.5 倍 ATR
  sl_atr_multiplier: 1.5  # 停損目標為 1.5 倍 ATR
  max_hold_periods: 20
  
# --- 滾動優化與回測設定 (用於 04_parameter_optimization.py) ---
walk_forward_optimization:
  n_trials: 50
  training_days: 270      # 縮短為約 9 個月
  validation_days: 90     # 縮短為約 3 個月
  testing_days: 45        # 縮短為約 1.5 個月
  step_days: 45           # 滾動步長也跟著縮短
  initial_cash: 100000.0
  commission: 0.001

# --- 交易策略參數 (用於 04_parameter_optimization.py) ---
strategy_params:
  entry_threshold: 0.45
